pages/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('page/<int:page_id>/<slug:page_slug>/', views.page_view, name="page"),
]

satnam_yoga/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls')),
    path('', include('users.urls')),
    path('', include('videos.urls')),
    path('', include('payments.urls')),
    path('', include('posts.urls')),
    path('', include('contact.urls')),
    path('', include('pages.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root= settings.STATIC_ROOT)

videos/urls.py
from django.urls import path
from . import views as video_views


urlpatterns = [
    path('', video_views.list_menu , name="feed"),
    path('videos/', video_views.categories_list , name="video_list_menu"),
    path('category/<int:category_id>/', video_views.category , name="category"),
    path('videos/<int:category_id>/<int:video_id>/', video_views.video_id_show , name="video_id_show"),
]

videos/models.py
from django.db import models
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from ckeditor.fields import RichTextField

# Create your models here.


class Category(models.Model):
    name= models.CharField(max_length=100, verbose_name= "Nombre")
    created = models.DateTimeField(auto_now_add= True);
    modified = models.DateTimeField(auto_now= True);

    class Meta:
        verbose_name= "Categoria"
        verbose_name_plural= "Categorias"
        ordering= ['-created']

    def __str__(self):
        """return video name!"""
        return self.name

class Video(models.Model):

    title = models.CharField(max_length= 100, verbose_name= "Titulo")

    image = models.ImageField(upload_to="user_images/", verbose_name= "Imagen", blank= True);
    categories= models.ManyToManyField(Category, verbose_name="Categorias")
    upload = models.TextField(verbose_name= "Vimeo embeded")
    description = RichTextField(verbose_name="Contenido")
    free_seen= models.BooleanField(default=False, null=False, verbose_name= "Muestra gratis")
    created = models.DateTimeField(auto_now_add= True);
    modified = models.DateTimeField(auto_now= True);

    class Meta:
        verbose_name= "Video"
        verbose_name_plural= "Vídeos"
        ordering= ['created']

    def __str__(self):
        """return video name!"""
        return self.title

@receiver(pre_delete, sender=Video)
def mymodel_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    try:
        instance.image.delete(False)
        instance.upload.delete(False)
    except:
        instance.upload.delete(False)

videos/views.py
import requests
import json
import stripe
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from videos.models import Video, Category
from users.models import Profile

#Video cipher vdocipher


# Create your views here.

def list_menu(request):
    user= request.user
    stripe.api_key = settings.STRIPE_SECRET_KEY
    month_subs_price= stripe.Price.retrieve(settings.STRIPE_PRICE_ID)
    firts_video =  None
    category= None
    try:
        firts_video =  Video.objects.filter(free_seen= True).first()
        category= firts_video.categories.first()
    except:
        pass

    return render(request, 'videos/feed.html', {'price_subs_month': "{0:.2f}".format(round(float(month_subs_price.unit_amount /100),3)), "firts_video": firts_video, "category": category,"user": user})


def categories_list(request):

    categories_content = Category.objects.all()
    # print(categories_content)
    subscription= False
    try:
        customer = Profile.objects.get(user=request.user)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        subscription = stripe.Subscription.retrieve(customer.stripeSubscriptionId)
    except:
        pass

    return render(request, 'videos/videos.html', {'categories_content': categories_content, 'subscription': subscription})


def category(request, category_id ):
    categories_content = Category.objects.all()
    category= get_object_or_404(Category,id= category_id)
    video_content = Video.objects.filter(categories=category).order_by('created')
    subscription= None
    try:
        customer = Profile.objects.get(user=request.user)
        stripe.api_key = settings.STRIPE_SECRET_KEY
        subscription = stripe.Subscription.retrieve(customer.stripeSubscriptionId)
        return render(request, "videos/videos.html", {"category": category, 'categories_content': categories_content, 'video_content': video_content, 'subscription': subscription})
    except Exception as e:
        return render(request, "videos/videos.html", {"category": category, 'categories_content': categories_content, 'video_content': video_content})




def video_id_show(request, category_id, video_id):
    categories_content = Category.objects.all()
    video= get_object_or_404(Video,id=video_id)
    category= get_object_or_404(Category,id= category_id)
    video_content = Video.objects.filter(categories=category).order_by('created')
    subscription= None
    try:
        customer = Profile.objects.get(user=request.user)
        # if customer.paypalSubscriptionId:
        #     access_token = get_paypal_token()
        #     headers = { 'Content-Type': 'application/json', 'Authorization': f'Bearer {access_token}' }
        #     url = f'https://api-m.paypal.com/v1/billing/subscriptions/{customer.paypalSubscriptionId}'
        #     subscription = requests.get(url, headers=headers).json()
        #     subscription['status'] =  subscription['status'].lower()
        # else:
        stripe.api_key = settings.STRIPE_SECRET_KEY
        subscription = stripe.Subscription.retrieve(customer.stripeSubscriptionId)

        return render(request, 'videos/videos.html', {
        "category": category,
        'categories_content': categories_content,
        'video_content': video_content,
        'video': video,
        'subscription': subscription
        })
    except Exception as e:
        return render(request, 'videos/videos.html', {
        "category": category,
        'categories_content': categories_content,
        'video_content': video_content,
        'video': video
        })

templates/videos/feed.html

{% extends "base.html" %}
<!-- {% load static %} -->



{% block head_content %}
  <title>Satnam Estudio | Escuela de Yoga en línea</title>
{% endblock %}

{% block container %}


  <div class="slideshow-container ">

    <div class="mySlides  fade_effect">
      <img src="{% static "img/portada_feed.jpg" %}" alt="">
      <div class="text">Tu escuela de yoga kundalini</div>
    </div>

    <div class="mySlides fade_effect">
      <img src="{% static "img/clases_en_vivo.jpg" %}" alt="">
      <div class="text">Clases en vivo </div>
    </div>

    <div class="mySlides fade_effect">
      <img src="{% static "img/portada_feed_4.jpg" %}" alt="">
    <div class="text">Empieza una nueva aventura!</div>
    </div>

    <!-- <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
    <a class="next" onclick="plusSlides(1)">&#10095;</a> -->

  </div>

  <div class="container main">

      <div class="welcome-feed d-flex flex-column align-items-center mt-3 mb-3">
        <h1>¿Qué es satnam Yoga?</h1>

        <iframe src="https://player.vimeo.com/video/542909470?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" style="width: 70vw; height: 60vh" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen title="Bienvenida"></iframe>
      </div>

      <section class="portada mb-3">
          <p class="portada_text">
            Diseñado para quienes buscan equilibrar su mundo exterior e interior.
            <br>
            <br>
            Sin importar la edad, ni experiencia.
            <br>
            <br>
            Es el yoga que se ajusta al ritmo de vida de cada quien.
            <br>
            <br>
            Fortalece tu cuerpo, tu mente y tu alma, y los une.
            <br>
            <br>
            Usa posturas, respiraciones, mantras y meditación, para identificar tus conflictos, eliminarlos y alcanzar tu
            realización.
          </p>
          <img src="{% static "img/portada_hatha.jpg" %}" alt="">
      </section>


  </div>

  <section class="membership container-fluid d-flex flex-column align-items-center pt-3">
        <h3>Membresía</h3>
        <h2>¡Empieza tu camino hoy!</h2>

        <div class="card_container mb-4">
          <div class="memebership_cards">
              <h3>Membresía</h3>
              <p class="membership_text">Accede a <span class="especial_text">todo el contenido</span>
              y toma clases de donde quiera que estes! A cualquier hora, cuantas veces quieras.</p>
          </div>

          <div class="memebership_cards">
              <h3>Acceso Ilimitado</h3>
              <p class="membership_cost">${{price_subs_month}} mxn</p>
              <p class="membership_text">mensual</p>
          </div>

          <div class="memebership_cards">
              <h3>Clases online</h3>
              <p class="membership_text">¡Mejora tu vida hoy!
              </p>
              <button type="button" name="button"><a id="membership_but_payment" href="{% url 'payment_home' %}">SUSCRIBIR MI MEMBRESIA</a></button>
          </div>
        </div>

        <h3 class="mt-4 mb-5">Continuamente subimos clases para ti !</h3>
   </section>

   <section class="online_clases">
     <h2>Clases en línea </h2>
     <p>Plataforma de enseñanza en línea.
        <br><br>
        Que tu agencia, la distancia o las prisas no sean excusas.
        <br><br>
        Conéctate a tus clases  desde  cualquier lugar, a cualquier <br>hora, cuantas veces quieras.
        <br><br>
        Descubre  que  puedes ejercitarte y, además, encontrar equilibrio <br> y mayor bienestar para vivir
        feliz.
        <br>
     </p>
     <button type="button" name="button"><a href="{% url 'payment_home' %}">ÚNETE AHORA</a></button>
   </section>

   <section class="class_benefition_cards mb-4">
     <h2 class="text-center mt-3 ">Clases completas de kundalini Yoga</h2>

     <div class="card_container">
        <div class="yoga_class_content">
          <img src="{% static "img/om.png" %}" alt="">
          <p class="clases_card_title">Kriya / series</p>
          <p>Ejercicios físicos y mentales, equilibria tu cuerpo, tu mente y alma.</p>
        </div>
        <div class="yoga_class_content">
          <img src="{% static "img/mind_yoga.png" %}" alt="">
          <p class="clases_card_title">Meditación</p>
          <p>Purifica tu mente, elimina la basura mental y conócete a ti  mismo.</p>
        </div>
        <div class="yoga_class_content">
          <img src="{% static "img/breathe.png" %}" alt="">
          <p class="clases_card_title">Respiración / Pranayama</p>
          <p>Revitaliza tu energía, regenera tu cuerpo e integra nuevos y mejores hábitos.</p>
        </div>
     </div>
   </section>

   <section class="beneficios_yoga">
     <h1 class="mb-3">Beneficios del kundalini yoga</h1>
     <div class="benefits_cards benefit_cards_des mt-3">
       <div class="benefit_card_item">
         <img src="{% static "img/cerebro.png" %}" alt="">
         <h3>Fortalece</h3>
         <p>Tu sistema nervioso</p>
       </div>
       <div class="benefit_card_item">
         <img src="{% static "img/sangre.png" %}" alt="">
         <h3>Activa </h3>
         <p>Tu circulación</p>
       </div>
       <div class="benefit_card_item">
         <img src="{% static "img/ley.png" %}" alt="">
         <h3>Equilibra</h3>
         <p>Tu sistema gandular</p>
       </div>
       <div class="benefit_card_item">
         <img src="{% static "img/brillar.png" %}" alt="">
         <h3>Desintoxica</h3>
         <p>Tu cuerpo</p>
       </div>

       <div class="benefit_card_item benefit_card_center">
        <img  src="{% static "img/beneficios_satnam.png" %}" alt="">
       </div>


       <div class="benefit_card_item">
         <img src="{% static "img/fuerte.png" %}" alt="">
         <h3>Fortalece</h3>
         <p>Tus músculos</p>
       </div>
       <div class="benefit_card_item">
         <img src="{% static "img/immune_system.png" %}" alt="">
         <h3>Fortalece</h3>
         <p>Tu sistema inmunológico</p>
       </div>
       <div class="benefit_card_item">
         <img src="{% static "img/yoga_icon.png" %}" alt="">
         <h3>Libera</h3>
         <p>el estrés</p>
       </div>
       <div class="benefit_card_item">
         <img src="{% static "img/digestion.png" %}" alt="">
         <h3>Mejora</h3>
         <p>Tu digestión</p>
       </div>
       <div class="benefit_card_item">
         <img src="{% static "img/sueno.png" %}" alt="">
         <h3>Mejora</h3>
         <p>tu calidad de sueño</p>
       </div>
       <div class="benefit_card_item">
         <img src="{% static "img/relief.png" %}" alt="">
         <h3>Alivia</h3>
         <p>la depresión  y ansiedad</p>
       </div>
     </div>
   </section>

   <section id="tomar_una_clase">
     <div>
      <h3>¿Estás listo para empezar?</h3>
      <p>Empieza a encontrate a ti mismo. <br> Un camino hacia el bienestar.</p>
     </div>
     {% if firts_video and category %}
     <button><a href="{% url 'video_id_show' category.id firts_video.id %}"">TOMAR UNA CLASE</a></button>
     {% endif %}
   </section>

{% endblock %}

templates/videos/menu.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
  <title>Videos Menu | Sat Nam Yoga</title>

{% endblock %}


{% block container %}

{% endblock %}

templates/videos/video_card.html
{% load static %}
{% if video %}
  {% if request.user.is_authenticated and subscription.status == "active" or request.user.is_authenticated and subscription.status == "suspended"  %}
    <h3 class="mt-2 mb-1">{{video.title}}</h3>
    <!-- <video  id="video" width="320" height="240" controls controlsList="nodownload">
     <source src="{{video.upload.url}}" type="video/mp4">
    </video> -->
    {{video.upload|safe}}
    <div class="video_description">{{video.description|safe}}</div>
  {% else %}
      {% if request.user.is_authenticated  or request.user.is_anonymous %}
      <h3 class="mt-2 mb-2">{{video.title}}</h3>
        {% if video.free_seen == True %}
          <!-- <video  id="video" width="320" height="240" controls controlsList="nodownload">
           <source src="{{video.upload.url}}" type="video/mp4">
          </video> -->
          {{video.upload|safe}}
          <div class="video_description">{{video.description|safe}}</div>
        {% else %}
          <div class="video_list_img_container">
              <img src="{% if video.image %} {{video.image.url}}{% else %}{% static "img/video-placeholder.png" %}{% endif %}" alt="" style="width:100%; filter: brightness(40%);">
              <p class="videos_list_center_text"><a href="{% url "payment_home" %}">Suscríbete</a> para poder reproducir el video</p>
          </div>
        {% endif %}
      {% endif %}
    {% endif %}

{% else %}
  {% if video_content %}
  <h3 class="mt-2 mb-2">{{video_content.first.title}}</h3>
  {% if video_content.first.free_seen == True or subscription.status == "active" or subscription.status == "suspended" %}
    <!-- <video  id="video" width="320" height="240" controls controlsList="nodownload">
     <source src="{{video_content.first.upload.url}}" type="video/mp4">
    </video> -->
    {{video_content.first.upload|safe}}
    <div class="video_description">{{video_content.first.description|safe}}</div>
    {% else %}
      <div class="video_list_img_container">
          <img src="{% if video_content.first.image %} {{video_content.first.image.url}}{% else %}{% static "img/video-placeholder.png" %}{% endif %}" alt="" style="width:100%; filter: brightness(40%);">
          <p class="videos_list_center_text"><a href="{% url "payment_home" %}">Suscríbete</a> para poder reproducir el video</p>
      </div>
    {% endif %}
  {% endif %}
{% endif %}

templates/videos/video_card2.html
{% load static %}
{% if video %}
  {% if request.user.is_authenticated and subscription.status == "active" or request.user.is_authenticated and subscription.status == "suspended"  %}
    <h3 class="mt-2 mb-1">{{video.title}}</h3>
    <!-- <video  id="video" width="320" height="240" controls controlsList="nodownload">
     <source src="{{video.upload.url}}" type="video/mp4">
    </video> -->
    {{video.upload|safe}}
    <div class="video_description">{{video.description|safe}}</div>
  {% else %}
      {% if request.user.is_authenticated  or request.user.is_anonymous %}
      <h3 class="mt-2 mb-2">{{video.title}}</h3>
        {% if video.free_seen == True %}
          <!-- <video  id="video" width="320" height="240" controls controlsList="nodownload">
           <source src="{{video.upload.url}}" type="video/mp4">
          </video> -->
          {{video.upload|safe}}
          <div class="video_description">{{video.description|safe}}</div>
        {% else %}
          <div class="video_list_img_container">
              <img src="{% if video.image %} {{video.image.url}}{% else %}{% static "img/video-placeholder.png" %}{% endif %}" alt="" style="width:100%; filter: brightness(40%);">
              <p class="videos_list_center_text"><a href="{% url "payment_home" %}">Suscríbete</a> para poder reproducir el video</p>
          </div>
        {% endif %}
      {% endif %}
    {% endif %}

{% else %}
  {% if category.video_set.all %}
  <h3 class="mt-2 mb-2">{{category.video_set.all.first.title}}</h3>
  {% if category.video_set.all.first.free_seen == True or subscription.status == "active" or subscription.status == "suspended" %}

    {{category.video_set.all.first.upload|safe}}
    <div class="video_description">{{category.video_set.all.first.description|safe}}</div>
    {% else %}
      <div class="video_list_img_container">
          <img src="{% if category.video_set.all.first.image %} {{category.video_set.all.first.image.url}}{% else %}{% static "img/video-placeholder.png" %}{% endif %}" alt="" style="width:100%; filter: brightness(40%);">
          <p class="videos_list_center_text"><a href="{% url "payment_home" %}">Suscríbete</a> para poder reproducir el video</p>
      </div>
    {% endif %}
  {% endif %}
{% endif %}

templates/videos/videos.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
  <title>Satnam videos</title>
  <!-- #IMPORT The Ajaxso no-one can save the video with right click -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock %}


{% block container %}
<!-- <div id="loader" class="center"></div> -->


<script type="text/javascript">



  function chooseVideo(vid_id){
    var videos = document.getElementsByClassName("video_container");
         for (i = 0; i < videos.length; i++) {
              if (videos[i].id  != vid_id) {
                  videos[i].style.display= "none"
              }
         }
    var video = document.getElementById("video:" + vid_id);
    console.log(video);
             if (video.style.display== "block") {
                  video.style.display= "none"
             } else{
                video.style.display= "block"
             }
  }


  function revealVideos(cat_id, fv_id){

    var videos = document.getElementsByClassName("video_list_menu");
         for (i = 0; i < videos.length; i++) {
              if (videos[i].id  != cat_id) {
                  videos[i].style.display= "none"

              }
         }

    var video = document.getElementById("category:" + cat_id);
             if (video.style.display== "flex") {
                  video.style.display= "none"
             } else{
                video.style.display= "flex"
             }
    chooseVideo(fv_id)
  }


</script>


<section id= "video_father_container" class="container video-list-container mb-4">

  <div class="category_box" style="width: inherit">
      <h3 class="">Categorías:</h3>
        <ul class="m-0 p-0" style="width: inherit">
          {% for category in categories_content %}
          <!-- <a  class="category_element" style="text-decoration: none; color: #0d39a8; font-weight: bold; width: 100%;" onclick="make(event)" href="{% url 'category' category.id %}"><li style="list-style-type: none;; text-align: center" class="list-group-item"> {{category.name}}</li></a> -->
          <a  class="category_element" style="text-decoration: none; color: #0d39a8; font-weight: bold; width: 100%;" onclick="revealVideos({{category.id}},{{category.video_set.all.first.id}})" ><li style="list-style-type: none;; text-align: center" class="list-group-item"> {{category.name}}</li></a>
          <!-- video  -->
            <div  id="category:{{category.id}}" class="video_list_menu" >
                {% for video in category.video_set.all %}
                    <div id="video:{{video.id}}" class="video_container">
                      {% include "videos/video_card2.html" %}
                    </div>
                {% endfor %}
                <div class="" id="Video_list_displayer">
                    <hr id="video_list_line">
                      <ul style="width: 100%;">

                        {% for video in category.video_set.all %}
                        <!-- <li style="list-style-type: none; display: flex; align-items:center"> <i class="fa fa-circle" style="font-size: 8px; margin-right: 5px;" aria-hidden="true"></i><a style="text-decoration: none; margin-right: 5px;" href="{% url 'video_id_show' category.id video.id %}">{{video.title}}</a>{% if  video.free_seen == True %} Video gratis {% endif %}</li> -->
                        <li style="list-style-type: none; display: flex; align-items:center"> <i class="fa fa-circle" style="font-size: 8px; margin-right: 5px;" aria-hidden="true"></i><a style="text-decoration: none; margin-right: 5px;" onclick="chooseVideo({{video.id}})">{{video.title}}</a>{% if  video.free_seen == True %} Video gratis {% endif %}</li>
                        {% endfor %}
                      </ul>
                </div>
            </div>
            <!-- video  -->
          {% endfor %}
        </ul>
  </div>


</section>




{% endblock %}